apiVersion: apps/v1
kind: Deployment
metadata:
  name: tum-details
  labels:
    app: details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
        - name: details
          image: tum/details:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080